services:
  backend:
    build: ./backend
    environment:
      - PORT=4000
    ports:
      - '4000:4000'
    networks:
      - main

  client:
    build: ./client
    environment:
      - PORT=3001
      - RELATIONAL_DB_DESIGNER_BACKEND_URL=http://backend:4000
    ports:
      - '3000:3000'
    networks:
      - main

networks:
  main:
    driver: bridge